language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
script: nosetests
deploy:
  provider: pypi
  user: internaphosting
  password:
    secure: AIKktJdBFMa2uk1WS3Uv90ENBGVDDRemvWh65uWpBsKd4F0eyZqV0eXE8O0EIezmy0UUnYNfJXuodgFo4T1DxQ13tcNJ/mzmhrEZ76YmUed9Ndn6ijRNAYNnwOkymhQW9EuJwyI1cfRt0N/5jP5F3ild/w4+mDWn/TAM0v0LFUDaSqYAPuzAUD7mYqjqW0GbKbwkM2JpCbs2gv2ff41DBUKIH0wwcrIQf0EkyxSYsoZfmd9wyol59aXFIbRFr6cmS2fYiHt6opVqs/WOrEpXbvUIIz5SCatYU7Upy7Buj+Pinu3oEk73pskvxDlQkoLWUN66WyrbdniktS9epcnz9fx2zFQtx3sCECTTx5SNTdKD0xOh5NjDYwZlp0sRQVDwns5vkpatUVmi/wfVAAHH08I1DkOm4nMpE3OpEeE9RlLZbNntbDs6+uqC+yCvvVdE/H9ascLjj5totLZLYvf9U2Alc8V/9yxRlvnD6IB5fQAUeu0VZ7DwJ0TC0CJVP8Lempd9U4UwiT9SSITfEMFGKWF71xQNPsXGfEPSMJbqksSZ7B39BJfqs8oZADWZJtCLGRkCuJiBjALOSn5OwcFq2PT4kZ1EFCsBP9r5xlJpkrcPzSa05dmZ0ZtrPOVTJ8VvANDGTQ7o+dcR2YxQN+DOewNx+0FSraqbo8wVFPjHGXc=
  on:
    tags: true
    python: 2.7
    distributions: sdist bdist_wheel
    repo: internap/python-pymongomodem
